version: "3.7"
   
services:
  web:
    build: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web/src:/code
    ports:
      - 8000:8000
    env_file:
      - web/.env